/* -*- Mode: C; c-basic-offset:4 ; indent-tabs-mode:nil -*- */
/*
 * Copyright (c) 2004-2005 The Trustees of Indiana University and Indiana
 *                         University Research and Technology
 *                         Corporation.  All rights reserved.
 * Copyright (c) 2004-2014 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 * Copyright (c) 2004-2005 High Performance Computing Center Stuttgart,
 *                         University of Stuttgart.  All rights reserved.
 * Copyright (c) 2004-2005 The Regents of the University of California.
 *                         All rights reserved.
 * Copyright (c) 2006      Los Alamos National Security, LLC.  All rights
 *                         reserved.
 * Copyright (c) 2008-2015 Cisco Systems, Inc.  All rights reserved.
 * Copyright (c) 2009      Oak Ridge National Labs.  All rights reserved.
 * Copyright (c) 2010-2014 Los Alamos National Security, LLC.
 *                         All rights reserved.
 * Copyright (c) 2014      Hochschule Esslingen.  All rights reserved.
 * Copyright (c) 2015      Research Organization for Information Science
 *                         and Technology (RIST). All rights reserved.
 * Copyright (c) 2015      Mellanox Technologies, Inc.
 *                         All rights reserved.
 * Copyright (c) 2016      Intel, Inc. All rights reserved.
 * $COPYRIGHT$
 *
 * Additional copyrights may follow
 *
 * $HEADER$
 */

#include "ww_config.h"

#include "ww_types.h"
#include "src/mca/base/mca_base_var.h"
#include "src/runtime/ww_params.h"
#include "src/util/timings.h"

#if WW_ENABLE_TIMING
char *ww_timing_sync_file = NULL;
char *ww_timing_output = NULL;
bool ww_timing_overhead = true;
#endif

static bool ww_register_done = false;

int ww_register_params(void)
{
    if (ww_register_done) {
        return WW_SUCCESS;
    }

    ww_register_done = true;

#if WW_ENABLE_TIMING
    ww_timing_sync_file = NULL;
    (void) mca_base_var_register ("ww", "ww", NULL, "timing_sync_file",
                                  "Clock synchronisation information generated by mpisync tool. You don't need to touch this if you use mpirun_prof tool.",
                                  MCA_BASE_VAR_TYPE_STRING, NULL, 0, 0,
                                  WW_INFO_LVL_9, MCA_BASE_VAR_SCOPE_ALL,
                                  &ww_timing_sync_file);
    if( ww_timing_clocksync_read(ww_timing_sync_file) ){
        ww_output(0, "Cannot read file %s containing clock synchronisation information\n", ww_timing_sync_file);
    }

    ww_timing_output = NULL;
    (void) mca_base_var_register ("ww", "ww", NULL, "timing_output",
                                  "The name of output file for timing information. If this parameter is not set then output will be directed into WW debug channel.",
                                  MCA_BASE_VAR_TYPE_STRING, NULL, 0, 0,
                                  WW_INFO_LVL_9, MCA_BASE_VAR_SCOPE_ALL,
                                  &ww_timing_output);

    ww_timing_overhead = true;
    (void) mca_base_var_register ("ww", "ww", NULL, "timing_overhead",
                                  "Timing framework introduce additional overhead (malloc's mostly)."
                                  " The time spend in such costly routines is measured and may be accounted"
                                  " (subtracted from timestamps). 'true' means consider overhead, 'false' - ignore (default: true).",
                                  MCA_BASE_VAR_TYPE_BOOL, NULL, 0, 0,
                                  WW_INFO_LVL_9, MCA_BASE_VAR_SCOPE_ALL,
                                  &ww_timing_overhead);
#endif

    return WW_SUCCESS;
}

int ww_deregister_params(void)
{
    ww_register_done = false;

    return WW_SUCCESS;
}
