/*
 * This file is autogenerated by autogen.pl. Do not edit this file by hand.
 */
#ifndef WW_FRAMEWORKS_H
#define WW_FRAMEWORKS_H

#include <Warewulf/mca/base/mca_base_framework.h>

extern mca_base_framework_t ww_src_base_framework;
extern mca_base_framework_t ww_bfrops_base_framework;
extern mca_base_framework_t ww_dl_base_framework;
extern mca_base_framework_t ww_installdirs_base_framework;
extern mca_base_framework_t ww_sec_base_framework;

static mca_base_framework_t *ww_frameworks[] = {
    &ww_src_base_framework,
    &ww_bfrops_base_framework,
    &ww_dl_base_framework,
    &ww_installdirs_base_framework,
    &ww_sec_base_framework,
    NULL
};

#endif /* WW_FRAMEWORKS_H */

